products/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from products import views

app_name = 'products'
product_api_router = SimpleRouter()
product_api_router.register('products/api', views.ProductAPIViewSet, 
    basename='products-api')


urlpatterns = [
    path('', views.IndexListView.as_view(), name='home'),
    path('<int:pk>/edit/', views.UpdateProductView.as_view(), name='edit_product'),
    path('<int:pk>/delete/', views.DeleteProductView.as_view(), name='delete_product'),
    path(
        'products/api/author/<int:pk>/',
        views.ProductsAPIDetailAuthor.as_view(),
        name='products_api_detail_author',
    ),
    path(
        'products/api/me/',
        views.LoggedInUserAPIView.as_view(),
        name='products_api_me',
    ),
    path(
        'products/api/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair',
    ),
    path(
        'products/api/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh',
    ),
    path(
        'products/api/token/verify/',
        TokenVerifyView.as_view(),
        name='token_verify',
    ),
]

urlpatterns += product_api_router.urls

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="register_create"),
    path('login/', views.login_view, name="login"),
    path('login/create/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<int:id>/', views.ProfileView, name="profile"),
    path('dashboard/', views.Dashboard, name="dashboard"),
    path('dashboard/product/new', views.DashboardProduct.as_view(), name="dashboard_product_create"),
    path('dashboard/product/delete', views.DashboardProductDelete.as_view(), name="dashboard_product_delete"),
    path('dashboard/product/<int:id>/edit/', views.DashboardProduct.as_view(), name="dashboard_product_edit"),
]

products/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from utils.django_utils_generic import generate_upload_path, random_string
from utils.django_utils_images import resize_image


class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = ('Category')
        verbose_name_plural = ('Categories')


class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    stock = models.IntegerField()
    description = models.TextField()
    cover = models.ImageField(upload_to=generate_upload_path, blank=True, null=True)
    is_published = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, max_length=110)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def __str__(self):
        return self.name
            
            
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug('name', 'slug')
        
        try:
            this = Product.objects.get(id=self.id) # type: ignore
            if this.cover != self.cover:
                this.cover.delete(save=False)
        except Product.DoesNotExist:
            pass

        super(Product, self).save(*args, **kwargs)

        if self.cover:
            resize_image(self.cover.path, 480)


    def generate_unique_slug(self, field_name, slug_field_name):
        base_slug = slugify(getattr(self, field_name), allow_unicode=True)
        slug = base_slug
        ModelClass = self.__class__
        while ModelClass.objects.filter(**{slug_field_name: slug}).exclude(id=self.id).exists(): # type: ignore
            slug = f"{base_slug}-{random_string(4)}"
        return slug

users/forms/product_form.py
from django import forms
from products.models import Product
from collections import defaultdict
from django.core.exceptions import ValidationError
from users.validators import UserProductValidator


class UserProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._myerrors = defaultdict(list)
    
    class Meta:
        model = Product
        fields = ['name', 'price', 'stock', 'description', 'cover',]
    
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        UserProductValidator(self.cleaned_data, ErrorClass=ValidationError)
        return super_clean

products/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Product


class IndexListView(ListView):
    template_name = 'index.html'
    model = Product
    paginate_by = 3
    ordering = '-id'
    
    def get_queryset(self):
        return Product.objects.filter(is_published=True).order_by(self.ordering)
    
    
# class CreateProductView(CreateView):
#     model = Product
#     template_name = 'product_form.html'
#     fields = ['name', 'stock', 'price', 'description']
#     success_url = reverse_lazy('products:home')
    
    
class UpdateProductView(UpdateView):
    model = Product
    template_name = 'product_form.html'
    fields = ['name', 'stock', 'price', 'description']
    success_url = reverse_lazy('products:home')
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_published = False
        self.object.save()
        return super().form_valid(form)
    
    
class DeleteProductView(DeleteView):
    model = Product
    template_name = 'product_del.html'
    success_url = reverse_lazy('products:home')

products/views/api_views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.response import Response
from django.shortcuts import get_object_or_404

from ..models import Product
from .permissions import IsOwner
from ..serializers import ProductSerializer, AuthorProductSerializer


class ProductAPIViewSet(ModelViewSet):
    queryset = Product.objects.filter(is_published=True).order_by('-created_at')
    serializer_class = ProductSerializer
    pagination_class = PageNumberPagination
    permission_classes = [IsAuthenticatedOrReadOnly]
    http_method_names = ['get', 'options', 'head', 'post', 'patch', 'delete']
    
    def get_object(self):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(
            Product.objects.filter(is_published=True).order_by('-created_at'),
            pk=pk
        )
        
        self.check_object_permissions(self.request, obj)
        return obj
    
    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return[IsOwner(),]
        
        return super().get_permissions()


class ProductsAPIDetailAuthor(ListAPIView):
    queryset = Product.objects.filter(is_published=True).order_by('-created_at')
    serializer_class = AuthorProductSerializer
    pagination_class = PageNumberPagination
    

class LoggedInUserAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        user_data = {
            "username": user.username,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "email": user.email,
        }
        return Response(user_data)

products/views/permissions.py
from rest_framework import permissions


class IsOwner(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        return obj.author == request.user
    
    
    def has_permission(self, request, view):
        return super().has_permission(request, view)

products/views/product_views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from ..models import Product


class IndexListView(ListView):
    template_name = 'index.html'
    model = Product
    paginate_by = 3
    ordering = '-id'
    
    def get_queryset(self):
        return Product.objects.filter(is_published=True).order_by(self.ordering)

    
class UpdateProductView(UpdateView):
    model = Product
    template_name = 'product_form.html'
    fields = ['name', 'stock', 'price', 'description']
    success_url = reverse_lazy('products:home')
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_published = False
        self.object.save()
        return super().form_valid(form)
    
    
class DeleteProductView(DeleteView):
    model = Product
    template_name = 'product_del.html'
    success_url = reverse_lazy('products:home')

products/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    <title>Products and Stuff</title>
</head>
<body>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

products/templates/index.html
{% extends 'global/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
  <div class="container">
    <h1>Products</h1>
  </div>

  <div class="container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Stock</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>

      <tbody>
        {% for product in page_obj %}
          <tr>
            <td class="product-name" data-image-url="{% if product.cover %}{{ product.cover.url }}{% endif %}">{{ product.name }}</td>
            <td>{{ product.stock }}</td>
            <td>${{ product.price }}</td>
            <td>
              {% if user.is_authenticated and product.author == user %}
                <a class="btn btn-warning" href="{% url 'products:edit_product' product.pk %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'products:delete_product' product.pk %}">Delete</a>
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4" class="text-center">
              <div class="alert alert-info" role="alert">
                No products have been added yet.
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'global/partials/pagination.html' %}
  </div>

  <div id="tooltip-image" style="display:none; position:fixed; width:250px; height:250px; border:1px solid #ccc; background:#fff;">
    <img id="tooltip-image-src" src="" alt="Product Image" style="width:100%; height:100%;" />
  </div>
{% endblock %}

<script src="{% static 'path/to/your/scripts.js' %}"></script>

products/templates/product_del.html
{% extends 'global/base.html' %}
{% load bootstrap4 %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you wan't to delete product: "{{ object }}" ?</p>
        {% buttons %}
            <button type="submit" class="btn btn-danger">Confirm</button>
            <button type="button" class="btn btn-warning">
                <a href="{% url "products:home" %}">Cancel</a>
            </button>
        {% endbuttons %}
    </form>
{% endblock content %}

products/templates/product_form.html
{% extends 'global/base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h1>Products: Edit</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <p>Observation: after you edit this product, it will be unpublished until an admin review it.</p>
    {% buttons %}
    <button type="submit" class="btn btn-primary">Save</button>
    <button type="button" class="btn btn-warning"><a href="{% url 'products:home' %}">Cancel</a></button>
    {% endbuttons %}
  </form>
{% endblock %}