products/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from products import views

app_name = 'products'
product_api_router = SimpleRouter()
product_api_router.register('products/api', views.ProductAPIViewSet, 
    basename='products-api')


urlpatterns = [
    path('', views.IndexListView.as_view(), name='home'),
    path('<int:pk>/edit/', views.UpdateProductView.as_view(), name='edit_product'),
    path('<int:pk>/delete/', views.DeleteProductView.as_view(), name='delete_product'),
    path(
        'products/api/author/<int:pk>/',
        views.ProductsAPIDetailAuthor.as_view(),
        name='products_api_detail_author',
    ),
    path(
        'products/api/me/',
        views.LoggedInUserAPIView.as_view(),
        name='products_api_me',
    ),
    path(
        'products/api/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair',
    ),
    path(
        'products/api/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh',
    ),
    path(
        'products/api/token/verify/',
        TokenVerifyView.as_view(),
        name='token_verify',
    ),
]

urlpatterns += product_api_router.urls

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="register_create"),
    path('login/', views.login_view, name="login"),
    path('login/create/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<int:id>/', views.ProfileView, name="profile"),
    path('dashboard/', views.Dashboard, name="dashboard"),
    path('dashboard/product/new', views.DashboardProduct.as_view(), name="dashboard_product_create"),
    path('dashboard/product/delete', views.DashboardProductDelete.as_view(), name="dashboard_product_delete"),
    path('dashboard/product/<int:id>/edit/', views.DashboardProduct.as_view(), name="dashboard_product_edit"),
]

users/forms/login.py
from django import forms
from utils.django_utils_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Type your username')
        add_placeholder(self.fields['password'], 'Type your password')
        
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

users/forms/product_form.py
from django import forms
from products.models import Product
from collections import defaultdict
from django.core.exceptions import ValidationError
from users.validators import UserProductValidator


class UserProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._myerrors = defaultdict(list)
    
    class Meta:
        model = Product
        fields = ['name', 'price', 'stock', 'description', 'cover',]
    
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        UserProductValidator(self.cleaned_data, ErrorClass=ValidationError)
        return super_clean

users/forms/profile_form.py
from django import forms
from users.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'address']

users/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from utils.django_utils_forms import add_attr, strong_password


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_attr(self.fields['username'], 'placeholder', 'Your username goes here')
        add_attr(self.fields['email'], 'placeholder', 'Your email goes here')
        add_attr(self.fields['first_name'], 'placeholder', 'Your first name goes here')
        add_attr(self.fields['last_name'], 'placeholder', 'Your last name goes here')
        
    username = forms.CharField(
        label='Username',
        help_text=(
            'Username must have letters, numbers or some of those @/./+/=/_. '
            'The length should be between 4 and 150 characters.'
        ),
        error_messages={
            'required': 'This field must not be empty',
            'min_length': 'Username must have at least 4 characters',
            'max_length': 'Username must 150 characters or less',
        },
        min_length=4, max_length=150,
    )
    email = forms.EmailField(
        error_messages={'required': 'Email field must not be empty'},
        label='Email',
        help_text='The email must be valid',
    )
    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        label='First name',
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        label='Last name',
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Your password'
        }),
        error_messages={
            'required': 'Password must not be empty'
        },
        help_text=(
            'Password must have at least one uppercase letter, one lowercase '
            'letter and one number. The length should be at least 8 characters.'
        ),
        validators=[strong_password],
        label='Password'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat your password here'
        }),
        error_messages={
            'required': 'Please, repeat your password'
        },
        label='Password2'
    )
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]
        
    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()
        
        if exists:
            raise ValidationError('User email is already in use', code='invalid',)
        
        return email
    
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        
        if password != password2:
            raise ValidationError({
                'password': 'Password and password 2 must match',
                'password2': 'Password and password 2 must match',
            })

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from users.forms.login import LoginForm
from users.forms.register_form import RegisterForm
from .models import Profile
from products.models import Product


def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)
    return render(request, 'pages/register_view.html',
        context={
            'form': form,
            'form_action': reverse('users:register_create'),
    })
    
    
def register_create(request):
    if not request.POST:
        raise Http404()
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)
    
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, 'Your user has been registered.')
        
        del(request.session['register_form_data'])
        return redirect('users:login')
    
    return redirect('users:register')


def login_view(request):
    form = LoginForm()
    return render(request, 'pages/login.html',
        context={
            'form': form,
            'form_action': reverse('users:login_create')
    })
    
    
def login_create(request):
    if not request.POST:
        raise Http404()
    
    form = LoginForm()
    
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        
        if authenticated_user is not None:
            messages.success(request, 'You are logged in.')
            login(request, authenticated_user)
        else:
            messages.error(request, 'Invalid credentials.')
    else:
        messages.error(request, 'Invalid username or password.')
        
    return redirect(reverse('users:dashboard'))


@login_required(login_url='users:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        messages.error(request, 'Invalid logout request')
        return redirect(reverse('users:login'))
    
    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Invalid logout user')
        return redirect(reverse('users:login'))
    
    logout(request)
    messages.success(request, 'Logged out succsesfully')
    
    return redirect(reverse('users:login'))


# TODO: CRIAR A DASHBOARD VIEW E OS TEMPLATES; LEMBRAR QUE O UNICO LOCAL ONDE 
# 'USERS' VIROU 'AUTHOR'
@login_required(login_url='users:login', redirect_field_name='next')
def dashboard(request):
    products = Product.objects.filter( 
        is_published=False, 
        author=request.User,
    )
    
    return render(
        request, 'pages/dashboard.html',
        context={
            'products': products,
        }
    )
    

class ProfileView(TemplateView):
    template_name = 'pages/profile.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        profile_id = context.get('id')
        profile = get_object_or_404(Profile.objects.filter(
            pk=profile_id
        ).select_related('author'), pk=profile_id)
        
        return self.render_to_response({
            **context,
            'profile': profile,
        })


users/views/authentication_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from users.forms.profile_form import ProfileForm
from users.forms.login import LoginForm
from users.forms.register_form import RegisterForm
from ..models import Profile


def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)
    return render(request, 'pages/register_view.html',
        context={
            'form': form,
            'form_action': reverse('users:register_create'),
    })
    
    
def register_create(request):
    if not request.POST:
        raise Http404()
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)
    
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, 'Your user has been registered.')
        
        del(request.session['register_form_data'])
        return redirect('users:login')
    
    return redirect('users:register')


def login_view(request):
    form = LoginForm()
    return render(request, 'pages/login.html',
        context={
            'form': form,
            'form_action': reverse('users:login_create')
    })
    
    
def login_create(request):
    if request.method != 'POST':
        raise Http404()

    form = LoginForm(request.POST)

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            messages.success(request, 'You are logged in.')
            login(request, authenticated_user)
            return redirect(reverse('users:dashboard'))
        else:
            messages.error(request, 'Invalid credentials.')
    else:
        messages.error(request, 'Invalid username or password.')

    return redirect(reverse('users:login'))


@login_required(login_url='users:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        messages.error(request, 'Invalid logout request')
        return redirect(reverse('users:login'))
    
    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Invalid logout user')
        return redirect(reverse('users:login'))
    
    logout(request)
    messages.success(request, 'Logged out successfully')
    
    return redirect(reverse('users:login'))
    

@require_http_methods(["GET", "POST"])
@login_required(login_url='users:login', redirect_field_name='next')
def ProfileView(request, id):
    profile = get_object_or_404(Profile, pk=id)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect(reverse('users:profile', kwargs={'id': id}))
        else:
            messages.error(request, 'Error updating profile. Please correct the errors below.')
    else:
        form = ProfileForm(instance=profile)
    
    context = {
        'profile': profile,
        'form': form,
    }
    return render(request, 'pages/profile.html', context)

users/views/dashboard_views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views import View
from django.urls import reverse

from products.models import Product
from users.forms.product_form import UserProductForm


@login_required(login_url='users:login', redirect_field_name='next')
def Dashboard(request):
    products = Product.objects.filter(
        is_published=False,
        author=request.user,
    )

    return render(
        request, 'pages/dashboard.html',
        context={
            'products': products,
        }
    )


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardProduct(View):
    def get_product(self, id=None):
        product = None

        if id is not None:
            product = Product.objects.filter(
                is_published=False,
                author=self.request.user,
                pk=id,
            ).first()

        return product

    def render_product(self, form, product=None):
        return render(
            self.request, 'pages/dashboard_product.html',
            context={
                'form': form,
                'product': product,
            }
        )

    def get(self, request, id=None):
        product = self.get_product(id)
        form = UserProductForm(instance=product)
        return self.render_product(form, product)

    def post(self, request, id=None):
        product = self.get_product(id)
        form = UserProductForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=product,
        )

        if form.is_valid():
            product = form.save(commit=False)

            product.author = request.user
            product.is_published = False

            if 'cover' in request.FILES:
                product.cover = request.FILES['cover']

            product.save()

            messages.success(request, 'Your product has been saved successfully')
            return redirect(reverse(
                'users:dashboard_product_edit', args=(product.id,)))

        return self.render_product(form, product)


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardProductDelete(DashboardProduct):
    def post(self, *args, **kwargs):
        product = self.get_product(self.request.POST.get('id'))
        product.delete()  # type: ignore
        messages.success(self.request, 'Product deleted successfully')
        return redirect(reverse('users:dashboard'))

users/templates/pages/dashboard.html
{% extends "global/base.html" %}
{% load bootstrap4 %}

{% block title %}Dashboard ({{ user }}) | {% endblock title %}

{% block content %}
    <div class="main-content container mt-5">
        <h2 class="mb-4">Dashboard ({{ user }})</h2>
        {% include "pages/partials/login_message.html" %}
        {% include "global/partials/messages.html" %}

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Your products</h3>
                <ul class="list-group list-group-flush">
                    {% for product in products %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'users:dashboard_product_edit' product.id %}">{{ product.name }}</a>
                            <form class="form-delete" method="POST"
                                  action="{% url "users:dashboard_product_delete" %}">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ product.id }}">
                                <button class="btn btn-link text-danger p-0" type="submit">
                                    🗑️
                                </button>
                            </form>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            <p class="mb-0">You don't have products, please create one.</p>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/pages/dashboard_product.html
{% extends 'global/base.html' %}
{% load bootstrap4 %}

{% block title %}
  Dashboard Product |
{% endblock %}

{% block content %}
  <div class="main-content container mt-5">
    <h2 class="mb-4">Dashboard Product</h2>
    {% include 'global/partials/messages.html' %}
    {% include 'pages/partials/login_message.html' %}

    <div class="card">
      <div class="card-body">
        {% include 'global/partials/form.html' %}
      </div>
    </div>
  </div>
{% endblock %}

users/templates/pages/login.html
{% extends "global/base.html" %}
{% load bootstrap4 %}

{% block title %}Login | {% endblock title %}

{% block content %}
    <div class="main-content container mt-5">
        <h2 class="mb-4">Login</h2>

        {% include "global/partials/messages.html" %}

        {% if not user.is_authenticated %}
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{% url 'users:login_create' %}">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Login</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

users/templates/pages/profile.html
{% extends 'global/base.html' %}
{% load bootstrap4 %}

{% block title %}
  Profile |
{% endblock %}

{% block content %}
  <div class="main-content center container">
    <h4 class="mt-4">Welcome to your profile: {{ profile.author.username }}</h4>
    {% include 'global/partials/messages.html' %}

    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Profile Information</h5>
        {% if profile.author.first_name %}
        <p><strong>First Name:</strong> {{ profile.author.first_name }}</p>
        {% else %}
        <p><strong>First Name:</strong> Not informed</p>
        {% endif %}
        {% if profile.author.last_name %}
        <p><strong>Last Name:</strong> {{ profile.author.last_name }}</p>
        {% else %}
        <p><strong>Last Name:</strong> Not informed</p>
        {% endif %}
        <p><strong>Email:</strong> {{ profile.author.email }}</p>
        <p><strong>Bio:</strong> {{ profile.bio }}</p>
        <p><strong>Address:</strong> {{ profile.address }}</p>

        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#editProfileForm" aria-expanded="false" aria-controls="editProfileForm">Edit Profile</button>

        <div class="collapse mt-3" id="editProfileForm">
          <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% url 'products:home' %}" class="btn btn-warning">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/pages/register_view.html
{% extends "global/base.html" %}
{% load bootstrap4 %}

{% block title %}Register | {% endblock title %}

{% block content %}
    <div class="main-content container mt-5">
        <h2 class="mb-4">Register</h2>

        {% include "global/partials/messages.html" %}

        <div class="card">
            <div class="card-body">
                <form method="post" action="{{ form_action }}">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Register</button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}